# .yarnrc.yml

packageExtensions:
  # The package "react-native-webview" is asking for a peer dependency.
  # We are telling Yarn to patch its package.json.
  # The "@*" means this patch will apply to any version of the package.
  "react-native-webview@*":
    peerDependenciesMeta:
      # We are declaring that its peer dependency on "react-native"
      # is optional for our project.
      "react-native":
        optional: true
